"""Storage layer."""

from datetime import date
from typing import Protocol, runtime_checkable

import pandas as pd


@runtime_checkable
class OHLCVStorageProtocol(Protocol):
    """Interface for OHLCV and indicator data persistence."""

    def store_ohlcv(self, ticker: str, df: pd.DataFrame) -> int: ...
    def get_ohlcv(self, ticker: str, start_date: date | None = None, end_date: date | None = None) -> pd.DataFrame: ...
    def get_latest_date(self, ticker: str) -> date | None: ...
    def store_indicators(self, ticker: str, df: pd.DataFrame) -> int: ...
    def get_indicators(self, ticker: str, names: list[str] | None = None) -> pd.DataFrame: ...
    def get_ticker_name(self, ticker: str) -> str | None: ...
    def store_ticker_name(self, ticker: str, name: str) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class WatchlistStorageProtocol(Protocol):
    """Interface for watchlist CRUD operations."""

    def create_watchlist(self, name: str) -> None: ...
    def delete_watchlist(self, name: str) -> None: ...
    def get_watchlists(self) -> list[dict]: ...
    def add_to_watchlist(self, name: str, ticker: str) -> None: ...
    def remove_from_watchlist(self, name: str, ticker: str) -> None: ...
    def get_watchlist_items(self, name: str) -> list[str]: ...
    def watchlist_exists(self, name: str) -> bool: ...


# Backwards compatibility
StorageProtocol = OHLCVStorageProtocol
